### ISSUE TITLE
Getting errors for simple example using create-react-app

### ISSUE THREAD

**Issue by ts-de** [diegohaz/singel#21]
I tried singel by using `create-react-app` and running `singel src/App.js` which gives me 
``` 
~/test-singel  singel src/App.js
/Users/tschloetel/test-singel/src/logo.svg:4
React.createElement(
^

ReferenceError: React is not defined
    at Object.<anonymous> (/Users/tschloetel/test-singel/src/logo.svg:1:1)
    at Module._compile (module.js:652:30)
    at loader (/usr/local/lib/node_modules/singel/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/singel/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/tschloetel/test-singel/src/App.js:2:1)
```

Then I created `Test.js` with the example from the docs: 

```
// bad - 2 elements
const Element = props => (
  <div {...props}>
    <span />
  </div>
);

// good
const Element2 = props => (
  <div {...props} />
);

// good - if Element is good
const Element3 = props => (
  <Element {...props} />
);
``` 
 I ran `singel Test.js` and get
```
usr/local/lib/node_modules/singel/dist/Logger.js:47
    const elementName = this.element.displayName || this.element.name;
                                     ^

TypeError: Cannot read property 'displayName' of undefined
    at Logger.start (/usr/local/lib/node_modules/singel/dist/Logger.js:47:38)
    at realPaths.forEach (/usr/local/lib/node_modules/singel/dist/cli.js:68:12)
    at Array.forEach (<anonymous>)
    at run (/usr/local/lib/node_modules/singel/dist/cli.js:57:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/singel/dist/cli.js:91:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by diegohaz** [comment]
Hey, @ts-de. Thank you for reporting it. The first error should be easy to fix. We are currently not ignoring svg files. We should add svg to src/babelConfig.js.

The second issue isn't actually an issue. We only support default exports. The examples in the Readme are there just as a reference. It's not supposed to be copied and pasted into a project.

Do you want to update babelConfig.js. I'll be glad to help you if you have any questions.

**Comment by ts-de** [comment]
Thanks @diegohaz. I added svg to `src/babelConfig.js` and I also played around to add the error. I am not sure if this is the best approach, though. The current error output is as follows: 
![screen shot 2018-07-08 at 12 44 23](https://user-images.githubusercontent.com/24268434/42419029-05d1f6ea-82ad-11e8-8f93-9bc81f2428cf.png)

But I think it would be cooler if the error was actually added to the reporting. I am just not sure how to, yet.
You can find both commits in https://github.com/ts-de/singel/commits/bugfix/issue%2321

Happy to hear your feedback

**Comment by diegohaz** [comment]
I think that's pretty good actually. We can try to add the error to the tester itself (so it would look like you thought), but it would require more changes since we wouldn't have the component name nor the component itself, which is currently required by ReactTester.
